---
title: "Introduction"
author: '[Hui Lin](https://scientistcafe.com) @Google</br>'
output:
  slidy_presentation:
  ioslides_presentation: default
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, error = F, warning =  F)
```

# [Course Website](https://smi2021.scientistcafe.com/) and [Github](https://github.com/happyrabbit/smi2021) 


<center>
<font size = "10">
https://smi2021.scientistcafe.com/
</font>
</center>

# Schedule

| Topic | Duration |
| :--- | :---: | 
| Introduction | 15 mins | 
| Feedforward Neural Networks | 60 mins | 
| Break | 10 mins | 
| Hands-on | 60 mins | 
| Break | 10 mins | 
| Convolutional Neural Networks | 40 mins | 
| Hands-on | 15 mins |
| Recurrent Neural Networks | 30 mins |

# Some other materials

- [Introduction to Data Science](http://scientistcafe.com/IDS/) (under review): the content of this workshop.  Here is the [GitHub Repo](https://github.com/happyrabbit/IntroDataScience/blob/master/README.md) for the book with links to code and notebooks.


deeplearning.ai provides in-depth education programs for different topics in AI

- [Deep Learning Specialization](https://www.deeplearning.ai/program/deep-learning-specialization/) provides a comprehensive introduction to the foundation of deep learning

Go beyond the foundations of deep learning to the nuances in applying AI to specific areas:

- [Natural Language Processing Specialization](https://www.deeplearning.ai/program/natural-language-processing-specialization/) focuses on NLP
- [AI for medicine](https://www.coursera.org/specializations/ai-for-medicine): course one of this specialization focuses on image processing in medicine.